name: Sync package-lock.json

on:
  push:
    branches:
      - main

permissions: # Grant write permissions to GitHub Actions
  contents: write

jobs:
  sync-lock-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and update package-lock.json
        run: |
          npm install
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package-lock.json
          git commit -m "Update package-lock.json to sync with package.json"
          git push
